name: Awesome Calculator CI build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist-path: ${{ steps.build-package.outputs.dist-path }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Unit Tests and generate coverage report
        run: |
          cd src
          python -m unittest discover -s tests -t .
          coverage run -m unittest discover -s tests -t .
          coverage report
          coverage html

      - name: Archive code coverage html report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: src/htmlcov

      - name: Run package creation
        id: build-package
        run: |
          cd src
          python -m pip install --user --upgrade build
          python -m build
          echo "::set-output name=dist-path::src/dist"

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: awesome-calculator
          path: src/dist

  install_package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: awesome-calculator
          path: ./dist

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install ./dist/*.whl

      - name: Verify installation
        run: |
          python -c 'import calculator; print("Package installed successfully!")'
